name: Self Tests

# Run workflow for any push to a branch/tag
on:
  push:
    branches:
      - '**'
    tags:
      - '**'

# Only permit one build per branch/tag
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  no-inputs:
    runs-on: ubuntu-latest
    name: Passes with No Inputs (Action Defaults used)
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          repository: telicent-oss/jena-fuseki-kafka

      - name: Setup Java
        uses: actions/setup-java@v5
        continue-on-error: true
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v7
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run action
        id: mvn-central-audit
        uses: Telicent-io/mvn-central-audit@v1

      - name: Verify Artifact Uploaded
        id: verify-artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ steps.mvn-central-audit.outputs.artifact-name }}
          skip-decompress: true

  matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Small Release passes
            repository: telicent-oss/jena-fuseki-kafka
            max-warnings: -1
            upload-report: true
            success: true
              
          - name: Small Release without Artifact Upload passes
            repository: telicent-oss/jena-fuseki-kafka
            max-warnings: -1
            upload-report: false
            success: true

          - name: Small Release with Warnings Limit fails
            repository: telicent-oss/jena-fuseki-kafka
            max-warnings: 0
            upload-report: true
            success: false
            
          - name: Large Release with Default Limits fails
            repository: telicent-oss/smart-caches-core
            max-warnings: -1
            upload-report: true
            success: false

          - name: Large Release with Increased Limits passes
            repository: telicent-oss/smart-caches-core
            max-files: 500
            max-size: 15000000 # 15MB
            max-warnings: -1
            upload-report: true
            success: true

          - name: Large Release with Disabled Limits passes
            repository: telicent-oss/smart-caches-core
            max-files: -1
            max-size: -1
            max-warnings: -1
            upload-report: true
            success: true

          - name: Release that requires custom Maven arguments
            repository: rvesse/airline
            maven-args: -Prelease
            max-files: 500
            upload-report: true
            success: true

          - name: Release that requires custom Maven arguments fails without them
            repository: rvesse/airline
            upload-report: true
            success: false

          - name: Fails on non-Maven repository
            repository: ${{ github.repository }}
            upload-report: true
            success: false
            
    name: ${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          repository: ${{ matrix.repository }}

      - name: Setup Java
        uses: actions/setup-java@v5
        continue-on-error: true
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v7
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run action
        id: mvn-central-audit
        uses: Telicent-io/mvn-central-audit@v1
        continue-on-error: true
        with:
          maven-args: ${{ matrix.maven-args }}
          max-files: ${{ case(matrix.max-files != '', matrix.max-files, 100) }}
          max-size: ${{ case(matrix.max-size != '', matrix.max-size, 10000000) }}
          max-warnings: ${{ matrix.max-warnings }}
          artifact-suffix: -${{ matrix.repository }}
          upload-report: ${{ matrix.upload-report }}

      - name: Verify Artifact Uploaded
        id: verify-artifact
        uses: actions/download-artifact@v8
        # Aritfact won't exist if action fails early in the audit process
        continue-on-error: true
        with:
          name: ${{ steps.mvn-central-audit.outputs.artifact-name }}
          skip-decompress: true

      - name: Verify No Artifact if Upload disabled
        if: ${{ matrix.upload-report == 'false' }}
        shell: bash
        run: |
          if [ -n "${{ steps.mvn-central-audit.outputs.artifact-id }}" ]; then
            echo "::error::Artifact ID output should not be set if configured to not upload it"
            exit 1
          fi
          if [ "${{ steps.verify-artifact.outcome }}" != "failure" ]; then
            echo "::error::Artifact was uploaded despite action being configured to not upload it"
            exit 2
          fi

      - name: Verify Success
        if: ${{ matrix.success == true }}
        run: |
          if [ "${{ steps.mvn-central-audit.outcome }}" != "success" ]; then
            echo "::error::Maven Central Audit failed when success was expected"
            exit 1
          fi

      - name: Verify Failure
        if: ${{ matrix.success != true }}
        run: |
          if [ "${{ steps.mvn-central-audit.outcome }}" != "failure" ]; then
            echo "::error::Maven Central Audit did not fail as expected"
          fi
